### ISSUE TITLE
docker compose error: no configuration file provided: not found

### ISSUE THREAD

**Issue by yuygfgg** [vnghia/nghe#361]
```
docker-compose logs nghe
no configuration file provided: not found
```
and for webui, I got connection refused.

I'm not sure what's configuration file here referring to.

docker-compose.yml:

```
services:
  nghe:
    image: ghcr.io/vnghia/nghe-musl:0.9.9
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      NGHE_DATABASE__URL: postgres://postgres:postgres@db:5432/postgres
      NGHE_DATABASE__KEY: a20eb15ac92cabfd96b81fb154b16357
    volumes:
      - /Users/a1/other/:/data/music/:ro
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
```
